apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: dev
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodeapp
        image: 10.108.235.232:8801/repository/docker-repo/nodejsapp:latest
        ports:
        - containerPort: 3000
        env:
          - name: HOST
            value: mysqlsvc

          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_USER

          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD

          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_DATABASE  
